### ISSUE TITLE
Update crashed

### ISSUE THREAD

**Issue by xmathe** [thomp/dired-launch#24] opened 2024-01-22 07:47 UTC
Jan. 22. 2024 upgrade crashes with an error referring to line 141 in dired-launch.el:

` (let ((buffer-name "dired-launch-output-buffer")`

**Comment by johanwiden** [comment] 2024-01-22 09:49
Missing right parentesis.

**Comment by xmathe** [comment] 2024-01-22 10:06
> Missing right parentesis.

No, parentheses within the defun block (lines 139-154) are correct.

**Comment by johanwiden** [comment] 2024-01-22 10:40
No, there is a missing parentesis in the latest commit.
This is also evident if one looks at the defun in emacs, in an elisp mode with matching colored parentesis.

**Comment by xmathe** [comment] 2024-01-22 12:27
Line 257. 
A right parenthesis is needed.
`    completions))) `

**Comment by thomp** [comment] 2024-01-23 06:18
This should be resolved by https://github.com/thomp/dired-launch/commit/5bd3e4b8068bc5c345965f09d46709e08e15d666

**Closed as completed by thomp** 2024-01-23 06:18 UTC

**Comment by johanwiden** [comment] 2024-01-23 09:21
Yes, the issue is now fixed.

**Comment by thomp** [comment] 2024-01-25 21:01
Thanks for confirming.
